version: '3.3'

services:
  web:
    image: wallet-web
    container_name: wallet-web
    restart: always
    depends_on:
      - postgres
      - redis
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /go/src/assignment_wallet
    environment:
      ReleaseMode: true
    ports:
      - "80:80"
    volumes:
      - .:/web
  postgres:
    image: postgres:17.0-alpine3.20
    container_name: wallet-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_USER=postgresql
      - POSTGRES_DB=wallet
    ports:
      - "5432:5432"
    volumes:
      - D:/data/postgresql_data:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: wallet-redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass redis
    environment:
      - REDIS_PORT=6379
    ports:
      - "6379:6379"
